"""updated uploads schema

Revision ID: 46886fd90e79
Revises: ca5888a5bc9e
Create Date: 2026-06-27 13:21:01.771001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46886fd90e79'
down_revision: Union[str, Sequence[str], None] = 'ca5888a5bc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('stored_filename', sa.String(), nullable=False))
    op.drop_constraint(op.f('uploads_original_filename_key'), 'uploads', type_='unique')
    op.create_unique_constraint(None, 'uploads', ['stored_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='unique')
    op.create_unique_constraint(op.f('uploads_original_filename_key'), 'uploads', ['original_filename'], postgresql_nulls_not_distinct=False)
    op.drop_column('uploads', 'stored_filename')
    # ### end Alembic commands ###
